title: Seite

icon: 📄

columns:
  main:
    width: 2/3
    fields:
      text:
        label: Text
        type: blocks

  sidebar:
    width: 1/3
    sections:
      images: sections/images
      meta: sections/meta
