type: fields
fields:
  customTitle:
    label: Eigener Titel
    type: text
    icon: title
  description:
    label: Beschreibung
    type: textarea
    buttons: false
    icon: text
  thumbnail:
    label: Vorschaubild
    type: files
    query: page.files.template("image")
    uploads: image
    multiple: false
