import * as fsp from "node:fs/promises";
import * as path from "node:path";
import { cwd } from "node:process";
import { render } from "@react-email/components";
import * as React from "react";
import {
  CommentNotificationEmail,
  CommentNotificationEmailProps,
} from "../templates/comment-notification";
import { PrecompileContext } from "../templates/components/If";

// Renders the template once with `{token}` placeholder props (React would
// entity-escape literal PHP tags), then rewrites the tokens to esc()'d PHP –
// a visitor-controlled value can never re-enter substitution.

const placeholderProps = Object.fromEntries(
  CommentNotificationEmailProps.map((propName) => [propName, `{${propName}}`]),
) as Record<(typeof CommentNotificationEmailProps)[number], string>;

let html = await render(
  React.createElement(
    PrecompileContext.Provider,
    { value: true },
    React.createElement(CommentNotificationEmail, placeholderProps),
  ),
);

const replacements: [string, string][] = [
  ["{/parentName}", "<?php endif ?>"],
  ["{#parentName}", "<?php if ($parentName !== null): ?>"],
  ["{name}", "<?= esc($name) ?>"],
  ["{articleTitle}", "<?= esc($article->title()->value()) ?>"],
  [
    "{time}",
    "<?= esc((string)($comment->date()->toDate('d.m.Y H:i') ?? '')) ?>",
  ],
  ["{preview}", "<?= esc($preview) ?>"],
  ["{panelUrl}", "<?= esc($panelUrl) ?>"],
  ["{articleUrl}", "<?= esc($articleUrl) ?>"],
  ["{parentName}", "<?= esc($parentName) ?>"],
  ["{parentExcerpt}", "<?= esc((string)$parentExcerpt) ?>"],
];

for (const [token, php] of replacements) {
  html = html.replaceAll(token, php);
}

const unresolvedTokens = html.match(/\{[#/]?\w+\}/g);
if (unresolvedTokens) {
  throw new Error(`Unmapped template tokens: ${unresolvedTokens.join(", ")}`);
}

const header = `
<?php
/**
 * @generated by emails/scripts/precompile.tsx from
 * emails/templates/comment-notification.tsx – do not edit.
 *
 * @var \\Kirby\\Cms\\Page $comment
 * @var \\Kirby\\Cms\\Page $article
 * @var string $name
 * @var string $preview
 * @var string $panelUrl
 * @var string $articleUrl
 * @var string|null $parentName
 * @var string|null $parentExcerpt
 */
?>
`.trimStart();

const outputFile = path.resolve(
  import.meta.dirname,
  "../../site/templates/emails/comment-notification.html.php",
);

await fsp.writeFile(outputFile, `${header}${html}\n`, "utf-8");

console.log(`Compiled ${path.relative(cwd(), outputFile)}`);
