title: Übersicht

tabs:
  content:
    label: Spiele
    icon: dashboard
    sections:
      games: sections/games

  blog:
    label: Blog
    icon: text
    sections:
      articles:
        type: pages
        label: Artikel
        parent: site.find("blog")
        template: article
        sortBy: date desc
        info: "{{ page.date.toDate('d.m.Y') }}"

  pages:
    label: Seiten
    icon: settings
    sections:
      pages:
        type: pages
        label: Seiten
        create: default
        image:
          back: white

  seo:
    label: SEO
    icon: search
    sections:
      seoFields:
        type: fields
        fields:
          description:
            extends: fields/description
            help: Eine kurze Beschreibung der Website. Wird für Seiten ohne eigene Beschreibung verwendet.
          thumbnail:
            extends: fields/thumbnail
            query: site.files.template('image')
            help: Wird für Seiten ohne eigenes Vorschaubild verwendet.

  images: tabs/images
