title: Übersicht

tabs:
  content:
    label: Spiele
    icon: dashboard
    sections:
      games: sections/games

  pages:
    label: Einstellungen
    icon: settings
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            label: Seiten
            create: default
            image:
              back: white

      - width: 1/2
        sections:
          meta:
            extends: sections/meta
            type: fields
            fields:
              thumbnail:
                query: site.files.template("image")

  images: tabs/images
